### ISSUE TITLE
Use GitHub release for latest CRAN version

### ISSUE THREAD

**Issue by maelle** [ropensci/ijtiff#14]
:wave: @rorynolan I saw there was an update of ijtiff on CRAN but no GitHub release yet. Reminding you about this as this will ensure the update is included in the next rOpenSci newsletter (see https://ropensci.org/blog/2021/04/16/latest-ropensci-news-digest/#new-versions for instance).

In case this is new to you: to do a GitHub release the easiest solution is running [`usethis::use_github_release()`](https://usethis.r-lib.org/reference/use_github_release.html) and to not forget to use [`usethis::use_release_issue()`](https://usethis.r-lib.org/reference/use_release_issue.html)

**Comment by rorynolan** [comment]
Hi @maelle 
Forgot to do this and did it now.
Thanks for your kind help as always, love being a part of rOpenSci!
Rory

**Comment by maelle** [comment]
Thank you! :pray:
