### ISSUE TITLE
Fails to install in Fedora

### ISSUE THREAD

**Issue by Enchufa2** [ropensci/ijtiff#15]
I see the following:

```
Found pkg-config! 
Found pkg-config cflags and/or libs for libtiff! 
Using PKG_CFLAGS= 
Using PKG_LIBS=-ltiff -lwebp -lzstd -ljpeg -lz -lm 
** finished configure for package 'ijtiff'
** libs
gcc -m64 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include   -fpic  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -c common.c -o common.o
In file included from common.c:1:
common.h:26:32: error: conflicting types for 'uint64_t'; have 'long long unsigned int'
   26 | typedef unsigned long long int uint64_t;
      |                                ^~~~~~~~
In file included from /usr/include/stdint.h:37,
                 from /usr/lib/gcc/x86_64-redhat-linux/11/include/stdint.h:9,
                 from /usr/include/tiffconf-64.h:13,
                 from /usr/include/tiffconf.h:9,
                 from /usr/include/tiff.h:28,
                 from common.h:5,
                 from common.c:1:
/usr/include/bits/stdint-uintn.h:27:20: note: previous declaration of 'uint64_t' with type 'uint64_t' {aka 'long unsigned int'}
   27 | typedef __uint64_t uint64_t;
      |                    ^~~~~~~~
make: *** [/usr/lib64/R/etc/Makeconf:168: common.o] Error 1
ERROR: compilation failed for package 'ijtiff'
```

See the complete log [here](https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-rawhide-x86_64/02296764-R-CRAN-ijtiff/builder-live.log.gz)

**Comment by Julien16** [comment]
I have the exact same error on several Arch/Arch-based machines
The ijtiff version installed by default is 2.2.6
I tried 2.2.5 and 2.2.4 but received the same error, that make me think that the problem is created by another piece of software...
Edit1:R 4.1.0 (so new version, same as in Fedora, and update earlier this week)
Edit2:same error in R 4.0.5

**Comment by rorynolan** [comment]
Hello,
I know what the issue is.
New version of libtiff assumes C99 and imports the stdint.h header. This is an easy fix but I'm not with my computer now. Will fix on Monday.
Thank you for pointing this out. 
Best,
Rory

**Comment by rorynolan** [comment]
I have fixed this now (I think).
Can you check please?

**Comment by Julien16** [comment]
Hi, sorry for the delay.
I just try to install it and it succeeded without issue (up-to-date Arch install and up-to-date R).
Thanks!

**Comment by rorynolan** [comment]
Great thanks @Julien16
Really appreciate you alerting me to this issue.
