### ISSUE TITLE
Ubuntu installation error

### ISSUE THREAD

**Issue by Marc-Girondot** [ropensci/ijtiff#19]
I have some problems to install the last version of ijtiff package in ubuntu 22.04.1 version (R 4.2.2). I get the same error both in R in terminal or in Rstudio: /usr/bin/ld: cannot find -lwebp: No such file or directory
I don't find any help in internet about this error.

sudo apt-get install libtiff5-dev

in terminal. No problem during installation.

Then in R:
install.packages("ijtiff")

Installation du package dans ‘/usr/local/lib/R/site-library’
(car ‘lib’ n'est pas spécifié)
essai de l'URL 'https://cloud.r-project.org/src/contrib/ijtiff_2.2.9.tar.gz'
Content type 'application/x-gzip' length 2433782 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

* installing *source* package ‘ijtiff’ ...
** package ‘ijtiff’ correctement décompressé et sommes MD5 vérifiées
** using staged installation
** preparing to configure package 'ijtiff' ...
Found pkg-config! 
Found pkg-config cflags and/or libs for libtiff! 
Using PKG_CFLAGS=-I/usr/include/x86_64-linux-gnu 
Using PKG_LIBS=-ltiff -lwebp -lzstd -llzma -ljpeg -ldeflate -lz -lm 
** finished configure for package 'ijtiff'
** libs
gcc -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-anRV6o/r-base-4.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c common.c -o common.o
gcc -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-anRV6o/r-base-4.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c init.c -o init.o
gcc -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-anRV6o/r-base-4.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c read.c -o read.o
gcc -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-anRV6o/r-base-4.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c utils.c -o utils.o
gcc -I"/usr/share/R/include" -DNDEBUG -I/usr/include/x86_64-linux-gnu     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-anRV6o/r-base-4.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c write.c -o write.o
gcc -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o ijtiff.so common.o init.o read.o utils.o write.o -ltiff -lwebp -lzstd -llzma -ljpeg -ldeflate -lz -lm -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -lwebp: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: ijtiff.so] Error 1
ERROR: compilation failed for package ‘ijtiff’
* removing ‘/usr/local/lib/R/site-library/ijtiff’
* restoring previous ‘/usr/local/lib/R/site-library/ijtiff’

Les packages source téléchargés sont dans
	‘/tmp/RtmpMuUequ/downloaded_packages’
Message d'avis :
Dans install.packages("ijtiff") :
  l'installation du package ‘ijtiff’ a eu un statut de sortie non nul

#############
Same output with 
devtools::install_github("ropensci/ijtiff")

#################

> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          2.2                         
year           2022                        
month          10                          
day            31                          
svn rev        83211                       
language       R                           
version.string R version 4.2.2 (2022-10-31)
nickname       Innocent and Trusting      

############ 
Ubuntu 22.04.1
############

> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        compiler_4.2.2    later_1.3.0       urlchecker_1.0.1 
 [5] prettyunits_1.1.1 profvis_0.3.7     remotes_2.4.2     tools_4.2.2      
 [9] digest_0.6.30     pkgbuild_1.3.1    pkgload_1.3.1     memoise_2.0.1    
[13] lifecycle_1.0.3   rlang_1.0.6       shiny_1.7.3       cli_3.4.1        
[17] curl_4.3.3        fastmap_1.1.0     withr_2.5.0       stringr_1.4.1    
[21] fs_1.5.2          htmlwidgets_1.5.4 devtools_2.4.5    rprojroot_2.0.3  
[25] glue_1.6.2        R6_2.5.1          processx_3.8.0    sessioninfo_1.2.2
[29] callr_3.7.3       purrr_0.3.5       magrittr_2.0.3    ps_1.7.2         
[33] promises_1.2.0.1  ellipsis_0.3.2    htmltools_0.5.3   usethis_2.1.6    
[37] mime_0.12         xtable_1.8-4      httpuv_1.6.6      stringi_1.7.8    
[41] miniUI_0.1.1.1    cachem_1.0.6      crayon_1.5.2

**Comment by rorynolan** [comment]
Hi @Marc-Girondot 
Thanks for the question.
Please try `sudo apt-get install -y libwebp-dev libzstd-dev` and then retry the installation.
Let me know how it goes.

**Comment by deboraycb** [comment]
I had the same issue and this solved it for me, thanks!
