### ISSUE TITLE
Repo topics

### ISSUE THREAD

**Issue by maelle** [ropensci/ijtiff#4]
:wave: again!

I've added a few repo topics see below

![image](https://user-images.githubusercontent.com/8360597/40724063-774db436-6420-11e8-86df-14bc53cf89e1.png)

Feel free to edit ("r" and "rstats" might seem useless but popular R package repos actually use them so I've added them to all ropensci packages)!

**Comment by rorynolan** [comment]
Yeah great!
Thanks for all your help.
