### ISSUE TITLE
SystemRequirements best practice

### ISSUE THREAD

**Issue by maelle** [ropensci/ijtiff#6]
:wave: @rorynolan!

As part of the consolidation of our guidance for package developers I've added a paragraph about system dependencies to https://ropensci.github.io/dev_guide/building.html#package-dependencies I see your package depends on `libtiff`.

Could you:

* check for it in the configure script and give a helpful error message if it cannot be found

* add the `libtiff` entry to sysreqsdb https://github.com/r-hub/sysreqsdb#sysreqs ?

Please ask me any question you might have! This part of the guide is brand-new, and sysreqsdb README was just updated, so they can certainly be improved. Thank you!

**Comment by rorynolan** [comment]
Hi @maelle 
Sorry for the tardy reply, I was having a nice holiday :-)
I've now included a configure script to check for an available `libtiff`. I'm not great at bash so it's a very hacky version of Jeroen's script. It took me a long time to make sense of it. It would be useful for the community to have a friendly intro to configure files somewhere, unfortunately I'm not the person to write it. I think "Writing R extensions" isn't great for this (as usual :-/).
I've also made the contribution to sysreqsdb (https://github.com/r-hub/sysreqsdb/pull/49).
Thanks for all of your continued help. I'm learning a lot.
Rory

**Comment by jeroen** [comment]
I'll try to improve it a bit, ok?

**Comment by rorynolan** [comment]
Hi @jeroen
What are you going to try to improve? Writing r exts or my sysreqsdb entry or my configure file? I'd be delighted for you to improve either but am very hesitant to ask the likes of yourself and Jim Hester for help because I presume you're snowed under with such pleas. I presume the real problem is that folks like me try to write r packages without being good at bash and at some point one actually does need to know bash.

**Comment by jeroen** [comment]
I rewrote the `configure` script.

**Comment by jeroen** [comment]
Make sure you `git pull` before working on your package again :)

**Comment by maelle** [comment]
Thanks @rorynolan for testing the instructions in dev_guide and thanks @jeroen for your input!

I'll update the guide a bit (_I_ don't know anything about the topic at all so I'm doing it a bit blindly, hence my being thankful for feedback).

I guess this issue can be closed once the sysreqsdb PR has been merged?

**Comment by rorynolan** [comment]
Hi @jeroen 
Thanks for all of your help with this `configure` script, couldn't have done that myself at all. It's beautifully done, it seems that someone who wanted to copy it would just have to change the 
```bash
# Library settings
PKG_CONFIG_NAME="libtiff-4"
PKG_DEB_NAME="libtiff-dev"
PKG_RPM_NAME="libtiff-devel"
PKG_BREW_NAME="libtiff"
PKG_TEST_HEADER="<tiff.h>"
PKG_LIBS="-ltiff -ljpeg -lz"
```
piece at the top.

@maelle and @jeroen 
With the above discussion in mind, I think it would be relatively easy to add a function to create an R function to create a `configure` file like this for checking for a library such as `libtiff`. R developers are always happier to deal with R functions rather than writing bash directly. I'm happy to write this function. Do you think this is a good idea?

**Comment by maelle** [comment]
Maybe relevant (and quite new) https://github.com/kevinushey/configure?

**Comment by jeroen** [comment]
@rorynolan the reason I am reluctant is that with configure scripts you need to really know what you are doing to understand how the C/C++ library works on different platforms and configurations. This part is not as forgiving as the R code... small bugs in the configure script can lead to bad things and can even get you kicked from CRAN :)

Authors could take this configure script as a starting point and adapt it for their library, but automating this in a way that ignores the intricacies of the C/C++ library that you are wrapping is a bad idea.

**Comment by rorynolan** [comment]
Fair enough @jeroen 
I think it would be helpful to have a walkthrough (line-by-line description of what is happening) of your `magick` `configure` file and maybe also of my `ijtiff` `configure` file on the rOpenSci dev guide rather than just a link to the `magick` `configure`. If you can make a walkthrough of yours, I can then make one of mine (which is basically a subset of yours). Just a suggestion, I realise you're super busy.

**Comment by maelle** [comment]
For the record, I replaced the link with a link to a less complex configure script, and added a link to all configure scripts of Jeroen's 🙈 

Rory, could you maybe say which part of the annotations of the script aren't clear enough? We could add a more annotated version to the Appendix of the guide I guess.

**Comment by rorynolan** [comment]
Hi @maelle 
Here's my very verbose edition of the `configure` file that you link to. Feel free to trim it or to do as you please with it. I've commented in caps where I don't know what's going on (just to highlight those bits, not to shout (-:).

```bash
#!/bin/bash
# Anticonf (tm) script by Jeroen Ooms (2017)
# This script will query 'pkg-config' for the required cflags and ldflags.
# pkg-config is a helper tool used when compiling applications and libraries.
# See https://www.freedesktop.org/wiki/Software/pkg-config/ for details.
# If pkg-config is unavailable or does not find the library, try setting
# INCLUDE_DIR and LIB_DIR manually via e.g:
# R CMD INSTALL --configure-vars='INCLUDE_DIR=/.../include LIB_DIR=/.../lib'

# Library settings
PKG_CONFIG_NAME="libwebp"  # pkg-config package name (found in pkg-config --list-all)
PKG_DEB_NAME="libwebp-dev"  # name of package in Debian (Ubuntu, etc.) repository
PKG_RPM_NAME="libwebp-devel"  # name of package in rpm (Fedora, EPEL) repository
PKG_CSW_NAME="libwebp_dev"  # name of package in Solaris repository
PKG_BREW_NAME="webp"  # name of package in homebrew (mac)
PKG_TEST_HEADER="<webp/encode.h>"  # a header file that the package uses
PKG_LIBS="-lwebp"  # package linker flags needed to provide package library to compiler
PKG_CFLAGS=""  # package C flags. Most commonly used to set define directives with `-D`.

# Use pkg-config if available (see start of script for details on pkg-config)
if [ $(command -v pkg-config) ]; then
  PKGCONFIG_CFLAGS=$(pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME})
  PKGCONFIG_LIBS=$(pkg-config --libs ${PKG_CONFIG_NAME})
fi

# If the $INCLUDE_DIR or $LIB_DIR variables are set, they need to be added into
# $PKG_CFLAGS or $PKG_LIBS similarly for $PKGCONFIG_CFLAGS and $PKGCONFIG_LIBS.
# Note that cflags may be empty in case of success
if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
  echo "Found INCLUDE_DIR and/or LIB_DIR!"
  PKG_CFLAGS="-I$INCLUDE_DIR $PKG_CFLAGS"
  PKG_LIBS="-L$LIB_DIR $PKG_LIBS"
elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
  echo "Found pkg-config cflags and libs!"
  PKG_CFLAGS=${PKGCONFIG_CFLAGS}
  PKG_LIBS=${PKGCONFIG_LIBS}
elif [[ "$OSTYPE" == "darwin"* ]]; then  # NO IDEA WHAT'S GOING ON ON MAC HERE
  if [ $(command -v brew) ]; then
    BREWDIR=$(brew --prefix)
  else
    curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
    source autobrew
  fi
  PKG_CFLAGS="-I$BREWDIR/opt/$PKG_BREW_NAME/include"
  PKG_LIBS="-L$BREWDIR/opt/$PKG_BREW_NAME/lib $PKG_LIBS"
fi

# For debugging
echo "Using PKG_CFLAGS=$PKG_CFLAGS"
echo "Using PKG_LIBS=$PKG_LIBS"

# Find compiler
# R CMD CONFIG is a shell script to get the values of basic R configure variables, 
# or the header and library flags necessary for linking against R.
CC=$(${R_HOME}/bin/R CMD config CC)
CFLAGS=$(${R_HOME}/bin/R CMD config CFLAGS)
CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)

# Test configuration: see if $PKG_TEST_HEADER can be successfully included 
# in a simple C program. If it cannot, it is not available to the package :-( and the variable
# $R_CONFIG_ERROR is set to 1. 
echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>&1 || R_CONFIG_ERROR=1;

# Output a message if $R_CONFIG_ERROR is equal to 1
if [ $R_CONFIG_ERROR ]; then
  echo "------------------------- ANTICONF ERROR ---------------------------"
  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
  echo " * rpm: $PKG_RPM_NAME (Fedora, EPEL)"
  echo " * csw: $PKG_CSW_NAME (Solaris)"
  echo " * brew: $PKG_BREW_NAME (OSX)"
  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
  echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
  echo "--------------------------------------------------------------------"
  exit 1;  # exit the script if indeed $R_CONFIG_ERROR is equal to 1
fi

# Write to Makevars
# DON'T KNOW WHAT'S GOING ON HERE (SOMETHING IS BEING WRITTEN TO MAKEVARS)
sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars

# Success
exit 0
```

**Comment by maelle** [comment]
ah very cool! @jeroen could you have a look at the annotated version above before I include it in the appendix?

**Comment by rorynolan** [comment]
Hi @maelle and @jeroen 
Recently I got around to submitting the latest `ijtiff` with its new `configure` script to CRAN. I got an email from Brian Ripley to say that it was failing on his MacOS. Here's what he had to say:

> This fails to install on macOS, where static libs are used:
** testing if installed package can be loaded
Error: package or namespace load failed for ‘ijtiff’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/Users/ripley/R/test-3.6/ijtiff/libs/ijtiff.so':
 dlopen(/Users/ripley/R/test-3.6/ijtiff/libs/ijtiff.so, 6): Symbol not found: _jpeg_resync_to_restart
 Referenced from: /Users/ripley/R/test-3.6/ijtiff/libs/ijtiff.so
The configure script is naive: please look at better examples such as R's own (and package tiff which assumes -ltiff -ljpeg and works).
On my macOS machine, libtiff-4.pc has
Name: libtiff
Description:  Tag Image File Format (TIFF) library.
Version: 4.0.7
Libs: -L${libdir} -ltiff
Libs.private: -llzma -ljpeg -lz
Cflags: -I${includedir}

> you need to try
pkg-config --static --libs libtiff-4
if pkg-config --libs libtiff-4 fails (you do not test it).

So basically: on mac, `pkg-config --libs libtiff-4` gives `-ltiff` whereas `pkg-config --static --libs libtiff-4` gives `-ltiff -llzma -ljpeg -lz`. As per @jeroen's `configure` script,  `-ltiff -ljpeg -lz` are needed. @jeroen's `configure` falls back to `-ltiff -ljpeg -lz` when `pkg-config` fails. The problem in this case was that `pkg-config` didn't outright fail, it just didn't do well enough. It needed the `--static`. I've now edited the `configure` script for `ijtiff` to check whether `pkg-config --libs libtiff-4` outputs the required `ltiff`, `ljpeg` and `lz`. If it does not, then it tries `pkg-config --static --libs libtiff-4` and then if that's still not good enough, it falls back upon the default `-ltiff -ljpeg -lz`.

I guess this should be what rOpenSci recommends to do in future?

@jeroen I'm pretty sure my script is working, but if you want to fix it or clean it up, feel free to push directly to the master branch of this repo.


PS: As per Ripley's comment, can either of you tell me where I could find R's own `configure` script? I didn't know where to look.

**Comment by rorynolan** [comment]
Hi @maelle and @jeroen 
Just an update on this. I've submitted to CRAN and the new `configure` script passes where the old one failed so I think it's good to go.
Rory :-)

**Comment by maelle** [comment]
Cool! I have never ever written a `configure` script myself, so can only say congrats!

**Comment by rorynolan** [comment]
Hi @maelle 
I've had to edit the configure script to allow for CRAN Solaris not having JBIG-KIT.
Just letting you know.

BTW the reason I keep updating you on this is that you were thinking of including it in the rOpenSci guide somehow. If that's no longer on the cards, that's totally cool. I realize this script is quite uninteresting and you probably don't want frequent updates on it.

**Comment by rorynolan** [comment]
Happy to reopen this issue but for now it seems to have run its race.

**Comment by Enchufa2** [comment]
I found trouble trying to package this for Fedora due to missing jpeg. If this package depends on jpeg, it should be declared as a system requirement too.

**Comment by rorynolan** [comment]
Hi @Enchufa2 
You are right. I've fixed that now.
Thanks for letting me know.
